channels:
  - anaconda
dependencies:
  - python = 3.7.6  # tensorflow is supported only till 3.7
  - tensorflow-gpu = 2.0.0  # conda version of tensorflow
  - pillow = 7.0.0  # for PIL.Image in tensorflow
  - opencv = 3.4.2  # opencv
  - flask = 1.1.1  # flask project
  - tqdm = 4.42.0 # tqdm progress-bar
